# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

config_mod <- function(org_corr, r, tol, verbose) {
    .Call('_perturbR_config_mod', PACKAGE = 'perturbR', org_corr, r, tol, verbose)
}

